// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: petclinic/vet.proto

package petclinic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateVetRequest) Reset() {
	*x = CreateVetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVetRequest) ProtoMessage() {}

func (x *CreateVetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVetRequest.ProtoReflect.Descriptor instead.
func (*CreateVetRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{0}
}

type CreateVetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateVetReply) Reset() {
	*x = CreateVetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVetReply) ProtoMessage() {}

func (x *CreateVetReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVetReply.ProtoReflect.Descriptor instead.
func (*CreateVetReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{1}
}

type UpdateVetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateVetRequest) Reset() {
	*x = UpdateVetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVetRequest) ProtoMessage() {}

func (x *UpdateVetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVetRequest.ProtoReflect.Descriptor instead.
func (*UpdateVetRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{2}
}

type UpdateVetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateVetReply) Reset() {
	*x = UpdateVetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVetReply) ProtoMessage() {}

func (x *UpdateVetReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVetReply.ProtoReflect.Descriptor instead.
func (*UpdateVetReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{3}
}

type DeleteVetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteVetRequest) Reset() {
	*x = DeleteVetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVetRequest) ProtoMessage() {}

func (x *DeleteVetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVetRequest.ProtoReflect.Descriptor instead.
func (*DeleteVetRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{4}
}

type DeleteVetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteVetReply) Reset() {
	*x = DeleteVetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVetReply) ProtoMessage() {}

func (x *DeleteVetReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVetReply.ProtoReflect.Descriptor instead.
func (*DeleteVetReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{5}
}

type GetVetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVetRequest) Reset() {
	*x = GetVetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVetRequest) ProtoMessage() {}

func (x *GetVetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVetRequest.ProtoReflect.Descriptor instead.
func (*GetVetRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{6}
}

type GetVetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVetReply) Reset() {
	*x = GetVetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVetReply) ProtoMessage() {}

func (x *GetVetReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVetReply.ProtoReflect.Descriptor instead.
func (*GetVetReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{7}
}

type ListVetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVetRequest) Reset() {
	*x = ListVetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVetRequest) ProtoMessage() {}

func (x *ListVetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVetRequest.ProtoReflect.Descriptor instead.
func (*ListVetRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{8}
}

type ListVetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVetReply) Reset() {
	*x = ListVetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVetReply) ProtoMessage() {}

func (x *ListVetReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVetReply.ProtoReflect.Descriptor instead.
func (*ListVetReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_proto_rawDescGZIP(), []int{9}
}

var File_petclinic_vet_proto protoreflect.FileDescriptor

var file_petclinic_vet_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2f, 0x76, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c,
	0x69, 0x6e, 0x69, 0x63, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x56, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
	0x56, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xf7, 0x02, 0x0a, 0x03, 0x56, 0x65, 0x74,
	0x12, 0x4b, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x12, 0x1f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a,
	0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x56, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65,
	0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x56, 0x65,
	0x74, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x56, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x07, 0x4c,
	0x69, 0x73, 0x74, 0x56, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74,
	0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63,
	0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x4d, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69,
	0x6e, 0x69, 0x63, 0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x77, 0x61, 0x73, 0x74, 0x69, 0x6c, 0x6c, 0x2f, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69,
	0x6e, 0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x65,
	0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x3b, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_petclinic_vet_proto_rawDescOnce sync.Once
	file_petclinic_vet_proto_rawDescData = file_petclinic_vet_proto_rawDesc
)

func file_petclinic_vet_proto_rawDescGZIP() []byte {
	file_petclinic_vet_proto_rawDescOnce.Do(func() {
		file_petclinic_vet_proto_rawDescData = protoimpl.X.CompressGZIP(file_petclinic_vet_proto_rawDescData)
	})
	return file_petclinic_vet_proto_rawDescData
}

var file_petclinic_vet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_petclinic_vet_proto_goTypes = []interface{}{
	(*CreateVetRequest)(nil), // 0: api.petclinic.CreateVetRequest
	(*CreateVetReply)(nil),   // 1: api.petclinic.CreateVetReply
	(*UpdateVetRequest)(nil), // 2: api.petclinic.UpdateVetRequest
	(*UpdateVetReply)(nil),   // 3: api.petclinic.UpdateVetReply
	(*DeleteVetRequest)(nil), // 4: api.petclinic.DeleteVetRequest
	(*DeleteVetReply)(nil),   // 5: api.petclinic.DeleteVetReply
	(*GetVetRequest)(nil),    // 6: api.petclinic.GetVetRequest
	(*GetVetReply)(nil),      // 7: api.petclinic.GetVetReply
	(*ListVetRequest)(nil),   // 8: api.petclinic.ListVetRequest
	(*ListVetReply)(nil),     // 9: api.petclinic.ListVetReply
}
var file_petclinic_vet_proto_depIdxs = []int32{
	0, // 0: api.petclinic.Vet.CreateVet:input_type -> api.petclinic.CreateVetRequest
	2, // 1: api.petclinic.Vet.UpdateVet:input_type -> api.petclinic.UpdateVetRequest
	4, // 2: api.petclinic.Vet.DeleteVet:input_type -> api.petclinic.DeleteVetRequest
	6, // 3: api.petclinic.Vet.GetVet:input_type -> api.petclinic.GetVetRequest
	8, // 4: api.petclinic.Vet.ListVet:input_type -> api.petclinic.ListVetRequest
	1, // 5: api.petclinic.Vet.CreateVet:output_type -> api.petclinic.CreateVetReply
	3, // 6: api.petclinic.Vet.UpdateVet:output_type -> api.petclinic.UpdateVetReply
	5, // 7: api.petclinic.Vet.DeleteVet:output_type -> api.petclinic.DeleteVetReply
	7, // 8: api.petclinic.Vet.GetVet:output_type -> api.petclinic.GetVetReply
	9, // 9: api.petclinic.Vet.ListVet:output_type -> api.petclinic.ListVetReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_petclinic_vet_proto_init() }
func file_petclinic_vet_proto_init() {
	if File_petclinic_vet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_petclinic_vet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_petclinic_vet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_petclinic_vet_proto_goTypes,
		DependencyIndexes: file_petclinic_vet_proto_depIdxs,
		MessageInfos:      file_petclinic_vet_proto_msgTypes,
	}.Build()
	File_petclinic_vet_proto = out.File
	file_petclinic_vet_proto_rawDesc = nil
	file_petclinic_vet_proto_goTypes = nil
	file_petclinic_vet_proto_depIdxs = nil
}
