// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: petclinic/vet_speciality.proto

package petclinic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVetSpecialityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateVetSpecialityRequest) Reset() {
	*x = CreateVetSpecialityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVetSpecialityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVetSpecialityRequest) ProtoMessage() {}

func (x *CreateVetSpecialityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVetSpecialityRequest.ProtoReflect.Descriptor instead.
func (*CreateVetSpecialityRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{0}
}

type CreateVetSpecialityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateVetSpecialityReply) Reset() {
	*x = CreateVetSpecialityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVetSpecialityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVetSpecialityReply) ProtoMessage() {}

func (x *CreateVetSpecialityReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVetSpecialityReply.ProtoReflect.Descriptor instead.
func (*CreateVetSpecialityReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{1}
}

type UpdateVetSpecialityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateVetSpecialityRequest) Reset() {
	*x = UpdateVetSpecialityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVetSpecialityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVetSpecialityRequest) ProtoMessage() {}

func (x *UpdateVetSpecialityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVetSpecialityRequest.ProtoReflect.Descriptor instead.
func (*UpdateVetSpecialityRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{2}
}

type UpdateVetSpecialityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateVetSpecialityReply) Reset() {
	*x = UpdateVetSpecialityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVetSpecialityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVetSpecialityReply) ProtoMessage() {}

func (x *UpdateVetSpecialityReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVetSpecialityReply.ProtoReflect.Descriptor instead.
func (*UpdateVetSpecialityReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{3}
}

type DeleteVetSpecialityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteVetSpecialityRequest) Reset() {
	*x = DeleteVetSpecialityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVetSpecialityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVetSpecialityRequest) ProtoMessage() {}

func (x *DeleteVetSpecialityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVetSpecialityRequest.ProtoReflect.Descriptor instead.
func (*DeleteVetSpecialityRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{4}
}

type DeleteVetSpecialityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteVetSpecialityReply) Reset() {
	*x = DeleteVetSpecialityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVetSpecialityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVetSpecialityReply) ProtoMessage() {}

func (x *DeleteVetSpecialityReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVetSpecialityReply.ProtoReflect.Descriptor instead.
func (*DeleteVetSpecialityReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{5}
}

type GetVetSpecialityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVetSpecialityRequest) Reset() {
	*x = GetVetSpecialityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVetSpecialityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVetSpecialityRequest) ProtoMessage() {}

func (x *GetVetSpecialityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVetSpecialityRequest.ProtoReflect.Descriptor instead.
func (*GetVetSpecialityRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{6}
}

type GetVetSpecialityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVetSpecialityReply) Reset() {
	*x = GetVetSpecialityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVetSpecialityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVetSpecialityReply) ProtoMessage() {}

func (x *GetVetSpecialityReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVetSpecialityReply.ProtoReflect.Descriptor instead.
func (*GetVetSpecialityReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{7}
}

type ListVetSpecialityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVetSpecialityRequest) Reset() {
	*x = ListVetSpecialityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVetSpecialityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVetSpecialityRequest) ProtoMessage() {}

func (x *ListVetSpecialityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVetSpecialityRequest.ProtoReflect.Descriptor instead.
func (*ListVetSpecialityRequest) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{8}
}

type ListVetSpecialityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVetSpecialityReply) Reset() {
	*x = ListVetSpecialityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petclinic_vet_speciality_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVetSpecialityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVetSpecialityReply) ProtoMessage() {}

func (x *ListVetSpecialityReply) ProtoReflect() protoreflect.Message {
	mi := &file_petclinic_vet_speciality_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVetSpecialityReply.ProtoReflect.Descriptor instead.
func (*ListVetSpecialityReply) Descriptor() ([]byte, []int) {
	return file_petclinic_vet_speciality_proto_rawDescGZIP(), []int{9}
}

var File_petclinic_vet_speciality_proto protoreflect.FileDescriptor

var file_petclinic_vet_speciality_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2f, 0x76, 0x65, 0x74, 0x5f,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x22,
	0x1c, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a,
	0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x0a, 0x1a, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x1c, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70,
	0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x56,
	0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1a, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a,
	0x16, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x97, 0x04, 0x0a, 0x0d, 0x56, 0x65, 0x74, 0x53,
	0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x69, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x69, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65,
	0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x29, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74,
	0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x69, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74,
	0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69,
	0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x60, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x26,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74,
	0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x63, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74,
	0x79, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69,
	0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56,
	0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x4d, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e,
	0x69, 0x63, 0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x61, 0x73, 0x74, 0x69, 0x6c, 0x6c, 0x2f, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e,
	0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x65, 0x74,
	0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x3b, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_petclinic_vet_speciality_proto_rawDescOnce sync.Once
	file_petclinic_vet_speciality_proto_rawDescData = file_petclinic_vet_speciality_proto_rawDesc
)

func file_petclinic_vet_speciality_proto_rawDescGZIP() []byte {
	file_petclinic_vet_speciality_proto_rawDescOnce.Do(func() {
		file_petclinic_vet_speciality_proto_rawDescData = protoimpl.X.CompressGZIP(file_petclinic_vet_speciality_proto_rawDescData)
	})
	return file_petclinic_vet_speciality_proto_rawDescData
}

var file_petclinic_vet_speciality_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_petclinic_vet_speciality_proto_goTypes = []interface{}{
	(*CreateVetSpecialityRequest)(nil), // 0: api.petclinic.CreateVetSpecialityRequest
	(*CreateVetSpecialityReply)(nil),   // 1: api.petclinic.CreateVetSpecialityReply
	(*UpdateVetSpecialityRequest)(nil), // 2: api.petclinic.UpdateVetSpecialityRequest
	(*UpdateVetSpecialityReply)(nil),   // 3: api.petclinic.UpdateVetSpecialityReply
	(*DeleteVetSpecialityRequest)(nil), // 4: api.petclinic.DeleteVetSpecialityRequest
	(*DeleteVetSpecialityReply)(nil),   // 5: api.petclinic.DeleteVetSpecialityReply
	(*GetVetSpecialityRequest)(nil),    // 6: api.petclinic.GetVetSpecialityRequest
	(*GetVetSpecialityReply)(nil),      // 7: api.petclinic.GetVetSpecialityReply
	(*ListVetSpecialityRequest)(nil),   // 8: api.petclinic.ListVetSpecialityRequest
	(*ListVetSpecialityReply)(nil),     // 9: api.petclinic.ListVetSpecialityReply
}
var file_petclinic_vet_speciality_proto_depIdxs = []int32{
	0, // 0: api.petclinic.VetSpeciality.CreateVetSpeciality:input_type -> api.petclinic.CreateVetSpecialityRequest
	2, // 1: api.petclinic.VetSpeciality.UpdateVetSpeciality:input_type -> api.petclinic.UpdateVetSpecialityRequest
	4, // 2: api.petclinic.VetSpeciality.DeleteVetSpeciality:input_type -> api.petclinic.DeleteVetSpecialityRequest
	6, // 3: api.petclinic.VetSpeciality.GetVetSpeciality:input_type -> api.petclinic.GetVetSpecialityRequest
	8, // 4: api.petclinic.VetSpeciality.ListVetSpeciality:input_type -> api.petclinic.ListVetSpecialityRequest
	1, // 5: api.petclinic.VetSpeciality.CreateVetSpeciality:output_type -> api.petclinic.CreateVetSpecialityReply
	3, // 6: api.petclinic.VetSpeciality.UpdateVetSpeciality:output_type -> api.petclinic.UpdateVetSpecialityReply
	5, // 7: api.petclinic.VetSpeciality.DeleteVetSpeciality:output_type -> api.petclinic.DeleteVetSpecialityReply
	7, // 8: api.petclinic.VetSpeciality.GetVetSpeciality:output_type -> api.petclinic.GetVetSpecialityReply
	9, // 9: api.petclinic.VetSpeciality.ListVetSpeciality:output_type -> api.petclinic.ListVetSpecialityReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_petclinic_vet_speciality_proto_init() }
func file_petclinic_vet_speciality_proto_init() {
	if File_petclinic_vet_speciality_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_petclinic_vet_speciality_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVetSpecialityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_speciality_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVetSpecialityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_speciality_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVetSpecialityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_speciality_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVetSpecialityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_speciality_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVetSpecialityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_speciality_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVetSpecialityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_speciality_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVetSpecialityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_speciality_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVetSpecialityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_speciality_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVetSpecialityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_petclinic_vet_speciality_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVetSpecialityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_petclinic_vet_speciality_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_petclinic_vet_speciality_proto_goTypes,
		DependencyIndexes: file_petclinic_vet_speciality_proto_depIdxs,
		MessageInfos:      file_petclinic_vet_speciality_proto_msgTypes,
	}.Build()
	File_petclinic_vet_speciality_proto = out.File
	file_petclinic_vet_speciality_proto_rawDesc = nil
	file_petclinic_vet_speciality_proto_goTypes = nil
	file_petclinic_vet_speciality_proto_depIdxs = nil
}
